/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface-bright": "#f7f9fb",
          "secondary-container": "#d0e1fb",
          "on-secondary-fixed-variant": "#38485d",
          "tertiary-fixed": "#ffdbcc",
          "on-secondary-container": "#54647a",
          "on-primary-container": "#dad7ff",
          "surface": "#f7f9fb",
          "surface-dim": "#d8dadc",
          "surface-container-lowest": "#ffffff",
          "on-surface-variant": "#464555",
          "primary-fixed": "#e2dfff",
          "on-primary-fixed-variant": "#3323cc",
          "on-tertiary-fixed-variant": "#7b2f00",
          "on-secondary": "#ffffff",
          "on-tertiary": "#ffffff",
          "inverse-on-surface": "#eff1f3",
          "inverse-primary": "#c3c0ff",
          "surface-container-low": "#f2f4f6",
          "on-tertiary-fixed": "#351000",
          "surface-tint": "#4d44e3",
          "primary-fixed-dim": "#c3c0ff",
          "inverse-surface": "#2d3133",
          "on-secondary-fixed": "#0b1c30",
          "surface-container-highest": "#e0e3e5",
          "error-container": "#ffdad6",
          "surface-container-high": "#e6e8ea",
          "secondary-fixed-dim": "#b7c8e1",
          "on-background": "#191c1e",
          "on-primary-fixed": "#0f0069",
          "surface-variant": "#e0e3e5",
          "tertiary-fixed-dim": "#ffb695",
          "on-error": "#ffffff",
          "on-primary": "#ffffff",
          "outline-variant": "#c7c4d8",
          "error": "#ba1a1a",
          "on-error-container": "#93000a",
          "outline": "#777587",
          "on-surface": "#191c1e",
          "secondary": "#505f76",
          "primary": "#3525cd",
          "surface-container": "#eceef0",
          "secondary-fixed": "#d3e4fe",
          "primary-container": "#4f46e5",
          "tertiary-container": "#a44100",
          "background": "#f7f9fb",
          "tertiary": "#7e3000",
          "on-tertiary-container": "#ffd2be"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Inter"],
          "body": ["Inter"],
          "label": ["Inter"],
          "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
